### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications (native works fine)

### ISSUE THREAD

**Issue by trusktr** [juggle/resize-observer#115] opened 2020-09-16 06:24 UTC
**Describe the bug**

I get the error

```
ResizeObserver loop completed with undelivered notifications.
```

in Chrome when I have replaced the native ResizeObserver with the polyfill. My code works fine with the native ResizeObserver, and I get the error only with the polyfill.

**To Reproduce**

Go to https://lume.io/docs/#/examples/hello3d

At the top of the example code, before any other code, paste the following:

```html
<script src="https://unpkg.com/@juggle/resize-observer@3.2.0/lib/exports/resize-observer.umd.js"></script>
<script>
  const RO = ResizeObserver
  window.ResizeObserver = RO.ResizeObserver
  window.ResizeObserverEntry = RO.ResizeObserverEntry
</script>
```

The preview on the right of the code updates automatically after code changes.

Now, simply make the window smaller by at least one pixel, and it'll trigger the error.

The code that uses the ResizeObserver is here:

https://github.com/lume/lume/blob/24debef2a8beed2ccff37f2091bcda049d9cd73c/packages/lume/src/core/Scene.ts#L481-L497

```js
			this.__resizeObserver = new ResizeObserver(changes => {
				for (const change of changes) {
					const {inlineSize, blockSize} = Array.isArray(change.borderBoxSize)
						? change.borderBoxSize[0]
						: change.borderBoxSize

					const isHorizontal = getComputedStyle(parent).writingMode.includes('horizontal')

					if (isHorizontal) this.__checkSize(inlineSize, blockSize)
					else this.__checkSize(blockSize, inlineSize)
				}
			})

			this.__resizeObserver.observe(parent)
```

**Expected behavior**

It should work like the native ResizeObserver (no error in that case). The example works before you paste that code, which is using `ResizeObserver` to detect container size changes.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Chrome

**Comment by trusktr** [comment] 2020-09-16 06:29
In case it helps, in that particular example, the ResizeObserver code is inside the `<i-scene>` custom element code, and it is observing the size of it's parent which happens to be the `<body>` in that example.

The `<body>` has `body, html {height: 100%; width: 100%}` styling applied to it, so it only changes size when the window resizes.

**Comment by trusktr** [comment] 2020-09-16 06:48
I did some investigation.

If I change the code to this:

```js
				this.__resizeObserver = new ResizeObserver(changes => {
					for (const change of changes) {
						this.__checkSize(Math.random() * 200, Math.random() * 200)
					}
				})
```

the error goes away. This means that somehow reading from the `ResizeObserverEntry` object (`change`) causes the issue. If I just pass random numbers along to the rest of my code in `__checkSize`, then there's no error.

This implies that the problem is indrectly triggered after having read the `change.borderBoxSize[0].inlineSize` and `change.borderBoxSize[0].blockSize` property paths. If those paths aren't accessed, then there's no error.

**Comment by trusktr** [comment] 2020-09-16 07:03
Not sure if this helps, but when the error happens (stepping through the code) I see `skippedTargets` contains a single element which happens to be the `<body>`. 

Also why may the error happen only when the window gets smaller, but not when it gets bigger? It doesn't seem that size values shrinking vs growing should have any effect on the outcome.

**Comment by trusktr** [comment] 2020-09-17 06:26
Oops! That example on lume.io, without pasting that code, has a different error if you don't paste the above code: it results in `ResizeObserver loop limit exceeded`, with native `ResizeObserver`, when shrinking the window.

I hadn't pushed my local changes (I have error with native code, error only with the polyfill).  I'll push a reproduction...

**Comment by trusktr** [comment] 2020-09-17 06:35
Ok, here's a reproduction you can try in your browser:

- Go to https://gitpod.io/#/https://github.com/lume/lume
- In the terminal pane, run
  ```
  git checkout juggle/resize-observer-issue-115
  npm install # this may take a while, especially on GitPod's server
  cd packages/lume
  npm run docs:build
  npm run docs:serve
  ```
- That will start a server, and GitPod (Theia IDE) will ask you if you want to open a preview window
- Then in the sidebar of the preview you can navigate to the "Hello 3D" example
- Shrink the height of the browser window to trigger the error

Note, GitPod editor also has an option to open the preview in a new tab, which can make it easier to inspect in separately in devtools.

**Comment by TremayneChrist** [comment] 2020-09-17 07:25
Just quickly before I dive into this. Have you tested on any other browsers, like Firefox? Would be good to see what happens there too.

**Comment by trusktr** [comment] 2020-09-17 07:40
Interesting, so on the computer I tested, I was on Chrome 84 Linux, when I get the error on `lume.io` after pasting the code.

On another computer that is still on Chrome 81 macOS, I do not get the error after pasting the code, and it works!

Here's a video in macOS Chrome 81, working:

![macos chrome 81 working](https://user-images.githubusercontent.com/297678/93435475-5e4e9f00-f87e-11ea-8076-6e7a0467f186.gif)

And Here's a video in Linux Chrome 84 not working:

![linux chrome 84 not working](https://user-images.githubusercontent.com/297678/93435987-0b291c00-f87f-11ea-943a-4776bfd9ad75.gif)

**Comment by trusktr** [comment] 2020-09-17 07:52
In Chrome 81, the example has an initial error, because it is trying to access inlineSize on an older ResizeObserverEntry's `contectRect` before the polyfill is applied. In Chrome 84, the example starts off working because it has the newer RO, before the polyfill is applied.

**Comment by trusktr** [comment] 2020-11-08 02:38
@TremayneChrist Hello! Did you get to try reproducing this yet?

**Comment by TremayneChrist** [comment] 2020-11-12 13:37
Hi @trusktr I'm now a bit overwhelmed by the amount of info in this issue and what is still valid or not 🙂 

I've tried your sample on Chrome 86 macOS and Firefox 82 macOS with no issues and checking back over the code the size must have changed during the observation callback for this error event to be fired. It might be worth stepping through [this code](https://github.com/juggle/resize-observer/blob/5fdab3b4705205281b7e5e5a45cbec42d9bff30b/src/ResizeObservation.ts#L31). This line is executed twice per cycle. If the `body` is being added to `skippedTargets` is should return different size results on each execution. Then we know (something) is causing the body size to be modified.

Looking through the code snippet you sent, I see there is a `_calcSize` and `needsUpdate`. Do any of these cause size updates?  I notice you are switching inline and block sizes based on the writing mode - the resize observer does this automatically, so essentially you are flipping them back to be incorrect. Some native versions still have a bug where this does not happen, so this might also be causing an issue.

**Comment by TremayneChrist** [comment] 2020-11-26 14:35
@trusktr did you manage to take another look?

**Comment by trusktr** [comment] 2021-02-24 06:47
I haven't had a chance to circle back to this yet. But ResizeObserver has been out since Safari 13.1 (Safari the new IE) for almost a year now, so maybe I'll just forget about it and hope people are upgraded by the time the project gains traction, if ever.

`this._calcSize` updates the size of an element (`this`) whenever that element's `size` property/attribute changes, or if its parent size property changes. The top level lume-scene element does a _calcSize only when the parent element (f.e. body) has changed sizes.

However, outside of lume-scene, nothing would be changing the body size. The lume-scene only observes the parent (with ResizeObserver), and then the new size calculations propagate down the lume tree, contained in the lume tree and not touching body or anything outside that tree.

needsUpdate just re-renders the graphics (either WebGL, or just CSS transforms on lume elements).

Anywho, this error only happens with the polyfill. Can't wait for users to be beyond Safari 13.0!

**Comment by TremayneChrist** [comment] 2021-05-06 11:34
Will close this as I cannot reproduce without forcefully resizing something during the loop. If you have time to send over a reproducible sample, feel free to reopen this!

**Closed as completed by TremayneChrist** 2021-05-06 11:34 UTC
