### ISSUE TITLE
Too many change detection triggered when we use ResizeObserver inside a polymer webcomponent placed in an Angular application

### ISSUE THREAD

**Issue by msbasanth** [juggle/resize-observer#81] opened 2019-10-23 11:01 UTC
**Describe the bug**
Too many change detection triggered when we use ResizeObserver inside a polymer webcomponent placed in an Angular application. At the same time if we are not using ResizeObserver Angular change detection's number is very few.

**To Reproduce**
1. Create an Angular application
2. Add a polymer webcomponent dropdown
3. Add a ResizeObserve instance inside 'ready()' call which will observe the webcomponent

`this.resizeObserver = new ResizeObserver((entries, observer) => {
      self.handleChange();
    });`

4. Enable resizeObserver only when dropdown is active (clicked and items shown)

**Expected behavior**
Change detection gets triggered only once for resize or UI modification.

**Sample Code**
      
```
if(this.active === true) {
        console.log("observing");
        this.resizeObserver.observe(_this);
      } else {
        console.log("unobserved");
        this.resizeObserver.unobserve(_this);
      }
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: IE11
 - Version: 11

**Additional context**
Why a webcomponent inside Angular is triggering too many change detections, when observe(element) is on. 
**Note:** The resize observer correctly notifies about the size change and we could respond to it. Only thing is the Angular change detection getting triggered more number of times (in IE11) when observe is ON.

Regards
Basanth

**Comment by TremayneChrist** [comment] 2019-10-23 14:47
Hi @msbasanth,
Can you create a sample repo for me to look at?

**Comment by TremayneChrist** [comment] 2019-10-25 10:21
Hi @msbasanth,

It would be good to get some more information on this. Could you tell me the angular version that you're using and also what polymer element you are adding the ResizeObserver on.

Maybe you could show something in CodeSandbox?
https://codesandbox.io/s/angular

**Comment by msbasanth** [comment] 2019-10-25 10:28
Sorry for the late reply. I will be back in office on Tuesday and will
update you with a sample.

Regards
Basanth

**Comment by TremayneChrist** [comment] 2019-11-19 21:02
Hey @msbasanth I'm going to close this for now as I cannot reproduce the issue. Feel free to reopen with a sample I can look at.

**Closed by TremayneChrist** 2019-11-19 21:02 UTC
